script: bash ./scripts.sh deploy
language: node_js
node_js:
- '6'
env:
  global:
  - GH_REF: github.com/websemantics/strong-together.git
  - secure: bLOo6DPgjgI94r+xgaleKar/Kuwidpo7GIzE6rbB27rwdbHgnojl2tl7z5tSnZ4rDZ3AO4JV1Acy0Ch6ah25SSZl8NV+TVSzxYiMfPSy9b0xQQ4okhqRqmq2lbk2g3Pq413zsP/ESL5IT2xXF1N6cW31jnIhnJ+K8KqNSRXJ3dns085ixCCQfbvtPmXIhXJJdlT9jrofWvFOmdSDfJgP69Lc7suUkPqAhs1AIj1I8GqOGv/Gn8ScN3zKCjd6C4nOUVr0bx60E8+kWQf2ge8FbTsaIb10b4oxrpzuQAy7bPRuTMgWFBzbJnYAcr9VRspRUkYr5X/Prt9toYHWIT94AM31BI7JOcZClkV9cwAKO4v2DSHl2LbJLcfVckndEzGSLz3YhWeTssgyuE8BNDuzfMU7FIx2tw1tW7RjevceZE3ZU4afsdHoB/2nb5RoNSA9kmPlwURuW8q2+Yb0RqPQub5rAkStBRCqh4pZQKpnOMPkcjD8DTumhll0hDF7CwCT63H7I9yEs8wHzSJFBT/Nr+7/jTXl3J/Yb+FZp+vyLcrwNX8QpfNLmxZn1vo11mkImSWVzNgJZuX/p64Mgl6nRqVOs58RZ/MtrE0eRdJv3Xxp3h1pMVpK92q2cQK9IQh6cGdeGskEZJLkr63bINJDmVZ8SjrmSWSz2zstdathFmQ=
